---
- name: My Very First Playbook
  hosts: vmrouters
  gather_facts: false
  
  tasks:
   - name: show ip address
     raw: show ip interface brief 

     register: print_output
   - debug: var=print_output.stdout_lines
